plugins {
    id 'java'
}

def env = new Properties()
def envFile = file('.env')
if (envFile.isFile() && envFile.canRead()) {
    envFile.withInputStream { env.load(it) }
    println env.getProperty("GITHUB_ACTOR") ?: ""
    println env.getProperty("GITHUB_TOKEN") ?: ""
}

repositories {
//    mavenLocal()
    mavenCentral()
    maven {
        name = "GitHubPackages"
        url = uri("https://maven.pkg.github.com/IngSisG10/printscript-tp1")
        credentials {
            username = env.getProperty("GITHUB_ACTOR")
            password = env.getProperty("GITHUB_TOKEN")
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

test {
    minHeapSize = "4m" // initial heap size
    maxHeapSize = "6m" // maximum heap size
}

configurations.all {
    resolutionStrategy.cacheChangingModulesFor(0, "seconds")
}

dependencies {
    testImplementation 'junit:junit:4.13.1'
    implementation 'com.ingsis.grupo10:printscript-interpreter:1.0.0-SNAPSHOT' changing true
    implementation 'com.ingsis.grupo10:printscript-parser:1.0.0-SNAPSHOT' changing true
    implementation 'com.ingsis.grupo10:printscript-lexer:1.0.0-SNAPSHOT' changing true
    implementation 'com.ingsis.grupo10:printscript-common:1.0.0-SNAPSHOT' changing true
    implementation 'com.ingsis.grupo10:printscript-formatter:1.0.0-SNAPSHOT' changing true
    implementation 'com.ingsis.grupo10:printscript-linter:1.0.0-SNAPSHOT' changing true
}

test {
    environment "BEST_FOOTBALL_CLUB", "San Lorenzo"
    useJUnit()
}
